// require('./syntax');
// require('./binding-and-assignment');
// require('./destructured-re-assignable-variables');
// require('./default-value');
// require('./rest-property');
// require('./assigning-to-new-variable-names');
// require('./computed-property-names');
// require('./invalid-identifiers');
// require('./prototype-chain-and-destructuring');
require('./swapping-variables');